<?php

namespace Database\Seeders;

use App\Models\PageSection;
use Illuminate\Database\Seeder;

class PageSectionSeeder extends Seeder
{
    public function run(): void
    {
        $sections = [
            [
                'id' => 'ps-home-hero',
                'page' => 'home',
                'section_key' => 'hero',
                'label' => 'Home — Hero banner',
                'eyebrow' => 'Lummina Aura',
                'title' => 'Light, pared back.',
                'body' => 'Hand-poured candles for quiet rooms — scent, vessel, and burn designed as one composition.',
                'body_secondary' => null,
                'image_url' => '/images/hero.svg',
                'cta_label' => 'View collection',
                'cta_href' => '/collection',
                'cta_secondary_label' => 'Our atelier',
                'cta_secondary_href' => '/about',
                'meta' => ['hasImage' => true, 'hasCtas' => true],
                'sort_order' => 1,
            ],
            [
                'id' => 'ps-home-featured',
                'page' => 'home',
                'section_key' => 'featured',
                'label' => 'Home — Featured candles',
                'eyebrow' => 'Selected works',
                'title' => 'Featured candles',
                'body' => null,
                'body_secondary' => null,
                'image_url' => null,
                'cta_label' => 'Browse all',
                'cta_href' => '/collection',
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => ['hasImage' => false, 'hasCtas' => true],
                'sort_order' => 2,
            ],
            [
                'id' => 'ps-home-atelier',
                'page' => 'home',
                'section_key' => 'atelier',
                'label' => 'Home — Atelier band',
                'eyebrow' => null,
                'title' => "Made slowly.\nMeant to linger.",
                'body' => 'Each pour begins with soy wax, cotton wick, and a fragrance composition balanced for clean burn and lasting presence.',
                'body_secondary' => null,
                'image_url' => '/images/atelier.svg',
                'cta_label' => null,
                'cta_href' => null,
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => ['hasImage' => true, 'hasCtas' => false],
                'sort_order' => 3,
            ],
            [
                'id' => 'ps-home-hamper',
                'page' => 'home',
                'section_key' => 'hamper_promo',
                'label' => 'Home — Gift hampers promo',
                'eyebrow' => 'Lummina Aura',
                'title' => 'Custom gift hampers',
                'body' => 'Compose candle, fragrance, color, and flowers — with optional logo packaging and live pricing.',
                'body_secondary' => null,
                'image_url' => null,
                'cta_label' => 'Build a hamper',
                'cta_href' => '/gifts',
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => ['hasImage' => false, 'hasCtas' => true],
                'sort_order' => 4,
            ],
            [
                'id' => 'ps-home-collection',
                'page' => 'home',
                'section_key' => 'collection_teaser',
                'label' => 'Home — Collection teaser',
                'eyebrow' => null,
                'title' => 'The collection',
                'body' => 'Six signature profiles — from soft linen mornings to deep cocoa nights.',
                'body_secondary' => null,
                'image_url' => null,
                'cta_label' => 'See full portfolio',
                'cta_href' => '/collection',
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => ['hasImage' => false, 'hasCtas' => true],
                'sort_order' => 5,
            ],
            [
                'id' => 'ps-about-main',
                'page' => 'about',
                'section_key' => 'main',
                'label' => 'About — Main content',
                'eyebrow' => 'Atelier',
                'title' => 'A practice of quiet light',
                'body' => 'Lummina Aura began as a studio experiment — fewer scents, better vessels, burns that hold a room without shouting.',
                'body_secondary' => "We pour in small batches using soy wax and cotton wicks. Fragrances are composed for clarity: warm woods, soft florals, clean linen, and evening spices.\n\nThe portfolio is curated, not crowded. Each candle is named, photographed, and stocked with the same care we give the pour itself.",
                'image_url' => '/images/atelier.svg',
                'cta_label' => null,
                'cta_href' => null,
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => ['hasImage' => true, 'hasCtas' => false],
                'sort_order' => 1,
            ],
            [
                'id' => 'ps-collection-intro',
                'page' => 'collection',
                'section_key' => 'intro',
                'label' => 'Collection — Intro',
                'eyebrow' => 'Portfolio',
                'title' => 'Collection',
                'body' => 'A quiet grid of hand-poured candles — hover to linger, click to explore.',
                'body_secondary' => null,
                'image_url' => null,
                'cta_label' => null,
                'cta_href' => null,
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => ['hasImage' => false, 'hasCtas' => false],
                'sort_order' => 1,
            ],
            [
                'id' => 'ps-gifts-hero',
                'page' => 'gifts',
                'section_key' => 'hero',
                'label' => 'Gifts — Hero',
                'eyebrow' => 'Lummina Aura',
                'title' => 'Custom gift hamper',
                'body' => 'Compose a candle, fragrance, color, and flowers — then add your logo to the packaging. Pricing updates as you build.',
                'body_secondary' => null,
                'image_url' => null,
                'cta_label' => null,
                'cta_href' => null,
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => ['hasImage' => true, 'hasCtas' => false],
                'sort_order' => 1,
            ],
            [
                'id' => 'ps-contact-main',
                'page' => 'contact',
                'section_key' => 'main',
                'label' => 'Contact — Studio details',
                'eyebrow' => 'Studio',
                'title' => 'Contact',
                'body' => null,
                'body_secondary' => null,
                'image_url' => null,
                'cta_label' => null,
                'cta_href' => null,
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => [
                    'hasImage' => false,
                    'hasCtas' => false,
                    'visit' => "Lummina Aura Studio\nBy appointment",
                    'email' => 'hello@lumminaaura.com',
                    'hours' => 'Monday – Saturday · 10:00 – 19:00',
                ],
                'sort_order' => 1,
            ],
            [
                'id' => 'ps-footer-main',
                'page' => 'footer',
                'section_key' => 'main',
                'label' => 'Site footer',
                'eyebrow' => null,
                'title' => 'Lummina Aura',
                'body' => 'Quiet light. Considered scent. Candles poured for interiors that prefer stillness over spectacle.',
                'body_secondary' => null,
                'image_url' => null,
                'cta_label' => null,
                'cta_href' => null,
                'cta_secondary_label' => null,
                'cta_secondary_href' => null,
                'meta' => [
                    'hasImage' => false,
                    'hasCtas' => false,
                    'hoursLabel' => 'Studio hours · Mon–Sat',
                    'hours' => '10:00 – 19:00',
                ],
                'sort_order' => 1,
            ],
        ];

        foreach ($sections as $section) {
            PageSection::query()->updateOrCreate(
                ['id' => $section['id']],
                $section
            );
        }
    }
}
